var hierarchy =
[
    [ "OpenTK.Audio.AudioCapture", "class_open_t_k_1_1_audio_1_1_audio_capture.html", null ],
    [ "OpenTK.Audio.AudioContext", "class_open_t_k_1_1_audio_1_1_audio_context.html", null ],
    [ "OpenTK.Audio.AudioException", "class_open_t_k_1_1_audio_1_1_audio_exception.html", [
      [ "OpenTK.Audio.AudioContextException", "class_open_t_k_1_1_audio_1_1_audio_context_exception.html", null ],
      [ "OpenTK.Audio.AudioDeviceException", "class_open_t_k_1_1_audio_1_1_audio_device_exception.html", null ],
      [ "OpenTK.Audio.AudioValueException", "class_open_t_k_1_1_audio_1_1_audio_value_exception.html", null ]
    ] ],
    [ "OpenTK.Audio.OpenAL.EffectsExtension", "class_open_t_k_1_1_audio_1_1_open_a_l_1_1_effects_extension.html", null ],
    [ "OpenTK.Audio.OpenAL.XRamExtension", "class_open_t_k_1_1_audio_1_1_open_a_l_1_1_x_ram_extension.html", null ],
    [ "OpenTK.AutoGeneratedAttribute", "class_open_t_k_1_1_auto_generated_attribute.html", null ],
    [ "OpenTK.BezierCurve", "struct_open_t_k_1_1_bezier_curve.html", null ],
    [ "OpenTK.BezierCurveCubic", "struct_open_t_k_1_1_bezier_curve_cubic.html", null ],
    [ "OpenTK.BezierCurveQuadric", "struct_open_t_k_1_1_bezier_curve_quadric.html", null ],
    [ "OpenTK.BindingsBase", "class_open_t_k_1_1_bindings_base.html", [
      [ "OpenTK.Graphics.GraphicsBindingsBase", "class_open_t_k_1_1_graphics_1_1_graphics_bindings_base.html", [
        [ "OpenTK.Graphics.ES10.GL", "class_open_t_k_1_1_graphics_1_1_e_s10_1_1_g_l.html", null ],
        [ "OpenTK.Graphics.ES11.GL", "class_open_t_k_1_1_graphics_1_1_e_s11_1_1_g_l.html", null ],
        [ "OpenTK.Graphics.ES20.GL", "class_open_t_k_1_1_graphics_1_1_e_s20_1_1_g_l.html", null ],
        [ "OpenTK.Graphics.OpenGL.GL", "class_open_t_k_1_1_graphics_1_1_open_g_l_1_1_g_l.html", null ]
      ] ]
    ] ],
    [ "OpenTK.Box2", "struct_open_t_k_1_1_box2.html", null ],
    [ "OpenTK.ContextExistsException", "class_open_t_k_1_1_context_exists_exception.html", null ],
    [ "OpenTK.ContextHandle", "struct_open_t_k_1_1_context_handle.html", null ],
    [ "OpenTK.DisplayDevice", "class_open_t_k_1_1_display_device.html", null ],
    [ "OpenTK.DisplayResolution", "class_open_t_k_1_1_display_resolution.html", null ],
    [ "OpenTK.FrameEventArgs", "class_open_t_k_1_1_frame_event_args.html", null ],
    [ "OpenTK.GLControl", "class_open_t_k_1_1_g_l_control.html", null ],
    [ "OpenTK.Graphics.Color4", "struct_open_t_k_1_1_graphics_1_1_color4.html", null ],
    [ "OpenTK.Graphics.ColorFormat", "struct_open_t_k_1_1_graphics_1_1_color_format.html", null ],
    [ "OpenTK.Graphics.GraphicsContextException", "class_open_t_k_1_1_graphics_1_1_graphics_context_exception.html", [
      [ "OpenTK.Graphics.GraphicsContextMissingException", "class_open_t_k_1_1_graphics_1_1_graphics_context_missing_exception.html", null ]
    ] ],
    [ "OpenTK.Graphics.GraphicsContextVersion", "class_open_t_k_1_1_graphics_1_1_graphics_context_version.html", null ],
    [ "OpenTK.Graphics.GraphicsMode", "class_open_t_k_1_1_graphics_1_1_graphics_mode.html", null ],
    [ "OpenTK.Graphics.GraphicsModeException", "class_open_t_k_1_1_graphics_1_1_graphics_mode_exception.html", null ],
    [ "OpenTK.Graphics.IGraphicsContext", "interface_open_t_k_1_1_graphics_1_1_i_graphics_context.html", [
      [ "OpenTK.Graphics.GraphicsContext", "class_open_t_k_1_1_graphics_1_1_graphics_context.html", null ]
    ] ],
    [ "OpenTK.Graphics.IGraphicsContextInternal", "interface_open_t_k_1_1_graphics_1_1_i_graphics_context_internal.html", [
      [ "OpenTK.Graphics.GraphicsContext", "class_open_t_k_1_1_graphics_1_1_graphics_context.html", null ]
    ] ],
    [ "OpenTK.GraphicsException", "class_open_t_k_1_1_graphics_exception.html", [
      [ "OpenTK.Graphics.GraphicsErrorException", "class_open_t_k_1_1_graphics_1_1_graphics_error_exception.html", null ]
    ] ],
    [ "OpenTK.Half", "struct_open_t_k_1_1_half.html", null ],
    [ "OpenTK.INativeWindow", "interface_open_t_k_1_1_i_native_window.html", [
      [ "OpenTK.NativeWindow", "class_open_t_k_1_1_native_window.html", [
        [ "OpenTK.GameWindow", "class_open_t_k_1_1_game_window.html", null ]
      ] ],
      [ "OpenTK.Platform.IGameWindow", "interface_open_t_k_1_1_platform_1_1_i_game_window.html", [
        [ "OpenTK.GameWindow", "class_open_t_k_1_1_game_window.html", null ]
      ] ]
    ] ],
    [ "OpenTK.Input.GamePad", "class_open_t_k_1_1_input_1_1_game_pad.html", null ],
    [ "OpenTK.Input.GamePadState", "struct_open_t_k_1_1_input_1_1_game_pad_state.html", null ],
    [ "OpenTK.Input.IInputDevice", "interface_open_t_k_1_1_input_1_1_i_input_device.html", [
      [ "OpenTK.Input.JoystickDevice", "class_open_t_k_1_1_input_1_1_joystick_device.html", null ],
      [ "OpenTK.Input.KeyboardDevice", "class_open_t_k_1_1_input_1_1_keyboard_device.html", null ],
      [ "OpenTK.Input.MouseDevice", "class_open_t_k_1_1_input_1_1_mouse_device.html", null ]
    ] ],
    [ "OpenTK.Input.IJoystickDriver", "interface_open_t_k_1_1_input_1_1_i_joystick_driver.html", [
      [ "OpenTK.Input.IInputDriver", "interface_open_t_k_1_1_input_1_1_i_input_driver.html", null ]
    ] ],
    [ "OpenTK.Input.IKeyboardDriver", "interface_open_t_k_1_1_input_1_1_i_keyboard_driver.html", [
      [ "OpenTK.Input.IInputDriver", "interface_open_t_k_1_1_input_1_1_i_input_driver.html", null ]
    ] ],
    [ "OpenTK.Input.IMouseDriver", "interface_open_t_k_1_1_input_1_1_i_mouse_driver.html", [
      [ "OpenTK.Input.IInputDriver", "interface_open_t_k_1_1_input_1_1_i_input_driver.html", null ]
    ] ],
    [ "OpenTK.Input.JoystickAxisCollection", "class_open_t_k_1_1_input_1_1_joystick_axis_collection.html", null ],
    [ "OpenTK.Input.JoystickButtonCollection", "class_open_t_k_1_1_input_1_1_joystick_button_collection.html", null ],
    [ "OpenTK.Input.JoystickButtonEventArgs", "class_open_t_k_1_1_input_1_1_joystick_button_event_args.html", null ],
    [ "OpenTK.Input.JoystickEventArgs", "class_open_t_k_1_1_input_1_1_joystick_event_args.html", [
      [ "OpenTK.Input.JoystickMoveEventArgs", "class_open_t_k_1_1_input_1_1_joystick_move_event_args.html", null ]
    ] ],
    [ "OpenTK.Input.KeyboardKeyEventArgs", "class_open_t_k_1_1_input_1_1_keyboard_key_event_args.html", null ],
    [ "OpenTK.Input.KeyboardState", "struct_open_t_k_1_1_input_1_1_keyboard_state.html", null ],
    [ "OpenTK.Input.MouseEventArgs", "class_open_t_k_1_1_input_1_1_mouse_event_args.html", [
      [ "OpenTK.Input.MouseButtonEventArgs", "class_open_t_k_1_1_input_1_1_mouse_button_event_args.html", null ],
      [ "OpenTK.Input.MouseMoveEventArgs", "class_open_t_k_1_1_input_1_1_mouse_move_event_args.html", null ],
      [ "OpenTK.Input.MouseWheelEventArgs", "class_open_t_k_1_1_input_1_1_mouse_wheel_event_args.html", null ]
    ] ],
    [ "OpenTK.Input.MouseState", "struct_open_t_k_1_1_input_1_1_mouse_state.html", null ],
    [ "OpenTK.KeyPressEventArgs", "class_open_t_k_1_1_key_press_event_args.html", null ],
    [ "OpenTK.Matrix2", "struct_open_t_k_1_1_matrix2.html", null ],
    [ "OpenTK.Matrix2d", "struct_open_t_k_1_1_matrix2d.html", null ],
    [ "OpenTK.Matrix2x3", "struct_open_t_k_1_1_matrix2x3.html", null ],
    [ "OpenTK.Matrix2x3d", "struct_open_t_k_1_1_matrix2x3d.html", null ],
    [ "OpenTK.Matrix2x4", "struct_open_t_k_1_1_matrix2x4.html", null ],
    [ "OpenTK.Matrix2x4d", "struct_open_t_k_1_1_matrix2x4d.html", null ],
    [ "OpenTK.Matrix3", "struct_open_t_k_1_1_matrix3.html", null ],
    [ "OpenTK.Matrix3d", "struct_open_t_k_1_1_matrix3d.html", null ],
    [ "OpenTK.Matrix3x2", "struct_open_t_k_1_1_matrix3x2.html", null ],
    [ "OpenTK.Matrix3x2d", "struct_open_t_k_1_1_matrix3x2d.html", null ],
    [ "OpenTK.Matrix3x4", "struct_open_t_k_1_1_matrix3x4.html", null ],
    [ "OpenTK.Matrix3x4d", "struct_open_t_k_1_1_matrix3x4d.html", null ],
    [ "OpenTK.Matrix4", "struct_open_t_k_1_1_matrix4.html", null ],
    [ "OpenTK.Matrix4d", "struct_open_t_k_1_1_matrix4d.html", null ],
    [ "OpenTK.Matrix4x2", "struct_open_t_k_1_1_matrix4x2.html", null ],
    [ "OpenTK.Matrix4x2d", "struct_open_t_k_1_1_matrix4x2d.html", null ],
    [ "OpenTK.Matrix4x3", "struct_open_t_k_1_1_matrix4x3.html", null ],
    [ "OpenTK.Matrix4x3d", "struct_open_t_k_1_1_matrix4x3d.html", null ],
    [ "OpenTK.Platform.IWindowInfo", "interface_open_t_k_1_1_platform_1_1_i_window_info.html", null ],
    [ "OpenTK.PlatformException", "class_open_t_k_1_1_platform_exception.html", null ],
    [ "OpenTK.Quaternion", "struct_open_t_k_1_1_quaternion.html", null ],
    [ "OpenTK.Quaterniond", "struct_open_t_k_1_1_quaterniond.html", null ],
    [ "OpenTK.Toolkit", "class_open_t_k_1_1_toolkit.html", null ],
    [ "OpenTK.Vector2", "struct_open_t_k_1_1_vector2.html", null ],
    [ "OpenTK.Vector2d", "struct_open_t_k_1_1_vector2d.html", null ],
    [ "OpenTK.Vector2h", "struct_open_t_k_1_1_vector2h.html", null ],
    [ "OpenTK.Vector3", "struct_open_t_k_1_1_vector3.html", null ],
    [ "OpenTK.Vector3d", "struct_open_t_k_1_1_vector3d.html", null ],
    [ "OpenTK.Vector3h", "struct_open_t_k_1_1_vector3h.html", null ],
    [ "OpenTK.Vector4", "struct_open_t_k_1_1_vector4.html", null ],
    [ "OpenTK.Vector4d", "struct_open_t_k_1_1_vector4d.html", null ],
    [ "OpenTK.Vector4h", "struct_open_t_k_1_1_vector4h.html", null ]
];